### ISSUE TITLE
Ryzen 7 2700X temperature offset?

### ISSUE THREAD

**Issue by shmerl** [groeck/lm-sensors#101]
Ryzen 7 2700X supposedly has +10°C temperature offset reported by the hardware sensors. Is k10temp currently taking it in account? I seem to get higher than expected temps with possibly this offset incldued:

    k10temp-pci-00c3
    Adapter: PCI adapter
    temp1:        +40.0°C  (high = +70.0°C)

That's on idle, jump on exact +10°C from 1700X with the same board and cooler.

Debian testing x86_64, kernel 4.15.11.

**Comment by groeck** [comment]
No, it doesn't. On my board (MSI B350M MORTAR), the offset is a whopping 60 °C. Something is fishy/wrong, but I have no idea what it might be. What is your board ?

**Comment by shmerl** [comment]
Asrock X370 Taichi (firmware 4.60).

**Comment by shmerl** [comment]
That's what I saw:

> To keep a "consistent fan policy," AMD is forcing 10C offset on the Ryzen 2700X and 2600X processors. This makes them report temperature a good 10C above what the sensor reads.

http://www.guru3d.com/articles-pages/amd-ryzen-7-2700x-review,7.html

**Comment by groeck** [comment]
1700X has a 20 degrees temperature offset, as is widely reported. I would just love to find out why my system reports a much larger offset. There must be some other configuration registers affecting that. Too bad that the information is only available under NDA.

**Comment by shmerl** [comment]
I'll try to find some official source about 2700X / 2600X.

**Comment by shmerl** [comment]
In regards to the weird offset with your MB, is it also messed up when you check the temperature inside the UEFI interface? If it's messed up there too, it's likely some bug with UEFI, so try contacting MSI about it.

**Comment by shmerl** [comment]
For now I just put this in `/etc/sensors.d/ryzen_2700x.conf`

    chip "k10temp-pci-00c3"
      compute temp1 @-10,@+10

**Comment by jatorvi** [comment]
Also MSI B350M Mortar, and the offset seems to be 60C

**Comment by groeck** [comment]
@jatorvi : Great, so I am at least not alone ;-). No idea what to do about it.

**Comment by DebauchedSloth** [comment]
I have a Crosshair VI with BIOS 6101, which is the latest AGESA version.  I also see a 60°C offset from what I see in UEFI.

**Comment by groeck** [comment]
Found the problem: If bit 20 of the raw register value is set, there is an additional 49 degrees C offset.

**Comment by groeck** [comment]
Please test https://github.com/groeck/k10temp

**Comment by shmerl** [comment]
Just built from source and installed with 4.15.11. 10°C offset is taken into account now, so it works well on Asrock X370 Taichi. Thanks!

Strangely though, firmware itself shows the temperature for me as if it has +20°C offset. I suppose it's their own bug.

**Comment by DebauchedSloth** [comment]
@groeck That looks perfect on my Crosshair VI.  Thanks!

**Comment by groeck** [comment]
Fix pushed to upstream kernel and into out-of-tree k10temp driver

**Comment by twifty** [comment]
I just built and installed, and having the same problem

sensors version 3.4.0+SVN with libsensors version 3.4.0+SVN

> amdgpu-pci-0a00
> Adapter: PCI adapter
> fan1:        1414 RPM
> temp1:        +32.0°C  (crit =  +0.0°C, hyst =  +0.0°C)
> 
> k10temp-pci-00c3
> Adapter: PCI adapter
> temp1:       +104.6°C  (high = +70.0°C)
> 
> asus-isa-0000
> Adapter: ISA adapter
> cpu_fan:        0 RPM

That looks like a 60 degree offset to me.

Ryzen 2700X on an ASUS Crosshair VII

**Comment by groeck** [comment]
@twifty: Please provide kernel log. I don't think you have the latest version of k10temp installed.

**Comment by twifty** [comment]
@groeck I'll check on that when I next get a chance. What is the latest version, I quickly checked the repo but the version doesn't seem to be listed there. Also, this is a Manjaro system, so I would think it should be using the latest version (especially since k10temp was last updated 3 months ago).

What do you need from my kernel log? I find journalctl difficult to use even on a good day :/

**Comment by groeck** [comment]
Exact kernel version as well as any output related to k10temp.

**Comment by twifty** [comment]
k10temp is installed, though if it's the latest version I don't know.

> [owen@twifty-lynx ~]$ modinfo k10temp
> filename:       /lib/modules/4.14.60-1-MANJARO/kernel/drivers/hwmon/k10temp.ko.xz
> license:        GPL
> author:         Clemens Ladisch <clemens@ladisch.de>
> description:    AMD Family 10h+ CPU core temperature monitor
> srcversion:     0493C0C32258FF858A10699
> alias:          pci:v00001022d00001463sv*sd*bc*sc*i*
> alias:          pci:v00001022d00001583sv*sd*bc*sc*i*
> alias:          pci:v00001022d00001533sv*sd*bc*sc*i*
> alias:          pci:v00001022d00001573sv*sd*bc*sc*i*
> alias:          pci:v00001022d0000141Dsv*sd*bc*sc*i*
> alias:          pci:v00001022d00001403sv*sd*bc*sc*i*
> alias:          pci:v00001022d00001603sv*sd*bc*sc*i*
> alias:          pci:v00001022d00001703sv*sd*bc*sc*i*
> alias:          pci:v00001022d00001303sv*sd*bc*sc*i*
> alias:          pci:v00001022d00001203sv*sd*bc*sc*i*
> depends:        
> retpoline:      Y
> intree:         Y
> name:           k10temp
> vermagic:       4.14.60-1-MANJARO SMP preempt mod_unload modversions 
> parm:           force:force loading on processors with erratum 319 (bool)

Exact kernel version was printed above, though for brevity:

> [owen@twifty-lynx ~]$ uname -r
> 4.14.60-1-MANJARO

While Manjaro does offer newer kernels, they are all a bit unstable.

There is nothing in my kernel log related to CPU / temp / k10, though [here it is](https://ufile.io/5vw3e).

**Comment by groeck** [comment]
This is the upstream version of k10temp, which, in v4.14.y, does not support handling temperature offsets.

**Comment by jonathonf** [comment]
@twifty Slight OT, but given you're running a 2700X you should probably move up to kernel 4.17 (or 4.18).

**Comment by twifty** [comment]
@jonathonf I tried the newer kernel but all my video playback stutters on them.
