### ISSUE TITLE
API documentation missing sensors_chip_name's bus definition

### ISSUE THREAD

**Issue by elliottjohnson** [groeck/lm-sensors#102]
Hello,

I'm writing a foreign function interface to libsensors and noticed that sensors_chip_name and sensors_bus_id structs are not specified in the documentation of the public API.  That isn't an issue in and of itself because the interface allows for the data in sensors_chip_name to be represented without the need for them to be public... until I was implementing the interface to sensors_get_adapter_name().

I do not see a way of calling that function without having knowledge that there is a "bus" member to sensors_chip_name that is a sensors_bus_id.  I've moved ahead and defined such a relationship, but thought I'd mention it here in case you have a use case that I didn't see for this public function.

Regards,
Elliott

**Comment by groeck** [comment]
Please feel free to submit patches to improve the documentation.
