### ISSUE TITLE
k10temp label

### ISSUE THREAD

**Issue by oyvinds** [groeck/lm-sensors#106]
/etc/sensors3.conf could include
chip "k10temp-pci-*"
	label temp1 "CPU temp"

I put that in /etc/sensors.d/k10temp.conf

I guess it's not extremely important since k10temp has one output so it's obvious temp1 is the CPU temp but there's no reason not to label it as the CPU temperature.

**Comment by groeck** [comment]
You can add that label yourself. Subsequent k10temp releases will provide Tctl and Tdie, and it does not seem to be a good idea to overwrite one with a preconfigured label.
