### ISSUE TITLE
Undeclared bus id referenced, sensors_init: Can't parse bus name

### ISSUE THREAD

**Issue by ypid** [groeck/lm-sensors#108]
Hi

There seems to be an issue with parsing the chip statement. Consider the following:

```
chip "jc42-i2c-0-1a"                                                                                                                                                            
    label temp1 "DIMM bank 0"
```

This will cause `sensors` to fail with:

> Error: File /etc/sensors.d/custom, line 1: Undeclared bus id referenced                                                                                                         
> sensors_init: Can't parse bus name

I was able to get libsensors working with the following workaround:

```
From 88f04cbfbd1f62fd2247a39d3745e9e1fecd1f7a Mon Sep 17 00:00:00 2001
From: Robin Schneider <ypid@riseup.net>
Date: Sun, 20 May 2018 21:18:15 +0200
Subject: [PATCH] Always return 0 in sensors_substitute_chip

Workaround for:

Error: File /etc/sensors.d/custom, line 1: Undeclared bus id referenced
sensors_init: Can't parse bus name
---
 lib/data.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/lib/data.c b/lib/data.c
index 937709f2..3628f852 100644
--- a/lib/data.c
+++ b/lib/data.c
@@ -227,6 +227,7 @@ static int sensors_substitute_chip(sensors_chip_name *name,
                    sensors_config_busses[i].bus.nr == name->bus.nr)
                        break;

+       return 0;
        if (i == sensors_config_busses_count) {
                sensors_parse_error_wfn("Undeclared bus id referenced",
                                        filename, lineno);
--
2.11.0
```

My C knowledge is to limited to provide an adequate patch unfortunately. Hope this helps.

**Comment by groeck** [comment]
Please check the "bus" statement in "man sensors3.conf" and update your configuration file accordingly.

**Comment by ypid** [comment]
Sorry for not reading the man page carefully enough. The following fixes it for me:

```
bus "i2c-0" "SMBus I801 adapter at f040"
```

Thanks for lm-sensors and your help!
