### ISSUE TITLE
ga-z170n-wifi

### ISSUE THREAD

**Issue by gbdu** [groeck/lm-sensors#12]
Hey, I can't seem to get my lm-sensors to recognize my cpu fan, I tried adding acpi_enforce_resources=lax to my boot line and re-running sensors-detect to no avail. The following is the output from sensors-detect http://pastebin.com/zryy0iEi 

What am I doing wrong?

Thank you

**Comment by groeck** [comment]
On Thu, Dec 22, 2016 at 04:40:46AM -0800, gbdu wrote:
> Hey, I can't seem to get my lm-sensors to recognize my cpu fan, I tried adding acpi_enforce_resources=lax to my boot line and re-running sensors-detect to no avail. The following is the output from sensors-detect http://pastebin.com/zryy0iEi
> 
Did you try to load the it87 driver ?

Guenter

**Comment by gbdu** [comment]
That worked, thank you!
