### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by raphinesse** [groeck/lm-sensors#15]
With the project site being down and all: how do I contribute? Where would I file issues?

[This repository was referred to as the place to get the source from](https://github.com/groeck/lm-sensors/issues/3#issuecomment-208839849). Does this mean that issues and PRs will be processed too?

**Comment by groeck** [comment]
Support is as time is available, and time is short nowadays. There is no guarantee that problems will be addressed in a timely basis. Feel free to submit issues here; they may or may not be addressed. I may accept pull requests, but again only as time is available.

**Comment by raphinesse** [comment]
Thanks for the clarification.
