### ISSUE TITLE
What happened to i2c-tools?

### ISSUE THREAD

**Issue by slokhorst** [groeck/lm-sensors#31]
Does anyone know what happened to i2c-tools? I think it was closely related to lm-sensors, and there are some links on the web pointing to https://github.com/groeck/i2c-tools as a new home, but that repository seems to have gone. 

This repository seems to still be quite active, so I was wondering if anyone here knows?

**Comment by groeck** [comment]
Its official home is https://git.kernel.org/pub/scm/utils/i2c-tools/i2c-tools.git

**Comment by slokhorst** [comment]
Thanks for the reply. :)
