### ISSUE TITLE
wrong cpu core number

### ISSUE THREAD

**Issue by heelsleeh** [groeck/lm-sensors#33]
cpu intel xeon E5 2699v4
i got 2 cpu 44 core 88 threads on my computer ,  lm_sensors show 29 cores
![screenshot from 2017-09-05 09-49-35](https://user-images.githubusercontent.com/24011272/30041847-da5b7234-91b2-11e7-917d-e544b2c7d139.png)

**Comment by groeck** [comment]
The output shows two CPUs with 22 cores each. CPU numbers are not sequential with recent Intel CPUs, and there are gaps. Given that, I don't see a problem. You should see the CPU number gaps with /proc/cpuinfo as well.

**Comment by heelsleeh** [comment]
sorry, i didn't notice is not sequential, thanks very much.
