### ISSUE TITLE
merge request for corsair axi powersupply support

### ISSUE THREAD

**Issue by cloudkitsch** [groeck/lm-sensors#5]
Hi, 
I came across some poorly maintained code for managing the fan speed and reading telemetry from my Corsair AX1200i cumulatively over the past couple of months and just confirmed that I can at least get the fan to turn on now with what little code I have. I'd be happy to dress it up some, but I'm looking for a better home for it, would there be a place for support for something like this in lm-sensors? It uses the cp210x serial module. I'm pretty sure this stupid power supply would never turn its fan on even under extremely hot conditions. Currently any Linux user with one of these could benefit, unless USB passthrough to a windows VM to run the windows driver / software (which sucks btw) is sufficient.

If anybody would like to have a look: https://github.com/cloudkitsch/cpsumon

Let me know I'll be happy to explain a bit more in detail, and even merge support in a pull request if it's welcomed.

Thanks, 
Paige

**Comment by cloudkitsch** [comment]
managed to get the fan speed up to 100% thats good enough for me, dont really care about the sound in my computer room just the heat in my apartment :/ frankly, I think the people who designed this psu have some screwed up priorities. Damn thing felt like it was about to catch on fire. 

```
[erratic:~/cpsumon]$ sudo ./cpsumoncli /dev/ttyUSB0                                                                                                                                                                             (master) 
Corsair AXi Series PSU Monitor
(c) 2014 Andras Kovacs - andras@sth.sze.hu
-------------------------------------------

Dongle name: USB to SMB Bridge (Firmware by Ross Fosler)
Dongle version: 0.9
PSU type: AX1200i
Fan mode: Fixed
Fan setting: 100 %
Fan speed: 1820.00 RPM
Temperature: 32.75 °C
Voltage: 124.00 V
Current: 1.75 A
Input power: 216.50 W
Output power: 202.00 W
Efficiency: 93.30 %
set_page (12v): set failed: 0, 9
[erratic:~/cpsumon]$     
```

**Comment by groeck** [comment]
I think it is better to keep that code as separate repository.

**Comment by okias** [comment]
generally lm_sensors support for Corsair AXI PSUs would be nice.

**Comment by stevef9432203** [comment]
One thing about lm_sensors are no unified monitoring applications and absolutely no simple way to add new drivers without kernel drivers. Considering the fairly widespread use userspace code these days, perhaps it's time  to allow simpler interface to lm_sensors is needed. As a system administrator it's easier
To monitor Winblowz then a high end linux server with multiple Gpus, or watercooling. DON'T use the excuse of desktop applets will do. Some very expensive monitoring tools can do it,as long as lm_sensors or plug-ins are supported. Netdata is better than most, but depends lm_sensors yet again.

Steven Fosre

**Comment by groeck** [comment]
stevef9432203@: Please feel free to design and implement the necessary code.

**Comment by yixophoenix** [comment]
How, how the fuck did mr ghost change fans from auto to fixed, why can't people give instructions for once in the linux community.
