### ISSUE TITLE
kmod cpuid seems to be required now...

### ISSUE THREAD

**Issue by noci2012** [groeck/lm-sensors#55]
It never struck me before, but it seems necesary the the cpuid kernel module is now required... 
(i never built it, wasn't a problem before) Now sensors detect fails:

Do you want to scan for them? This is totally safe. (YES/no):
modprobe: FATAL: Module cpuid not found in directory /lib/modules/4.14.12-gentoo
Failed to load module cpuid.
Silicon Integrated Systems SIS5595...                       No
VIA VT82C686 Integrated Sensors...                          No
VIA VT8231 Integrated Sensors...                            No
AMD K8 thermal sensors...                                   No
AMD Family 10h thermal sensors...                           No
AMD Family 11h thermal sensors...                           No
AMD Family 12h and 14h thermal sensors...                   No
AMD Family 15h thermal sensors...                           No
AMD Family 16h thermal sensors...                           No
AMD Family 15h power sensors...                             No
AMD Family 16h power sensors...                             No
Intel digital thermal sensor...                             No
Intel AMB FB-DIMM thermal sensor...                         No
Intel 5500/5520/X58 thermal sensor...                       No
VIA C7 thermal sensor...                                    No
VIA Nano thermal sensor...                                  No

is cpu id a requirement now?

**Comment by groeck** [comment]
The last time anything related to cpuid was changed in sensors-detect was back in 2011. Looking into the code, it is and always has been required. How else would the script read the CPU ID ? Closing.
