### ISSUE TITLE
Driver for IPMI BMC KCS

### ISSUE THREAD

**Issue by deric** [groeck/lm-sensors#69]
Hi,
I'm trying to compile `lm-sensors` on AMD EPYC machine.

```
# cat /proc/cpuinfo | grep "model name" | tail -n 1
model name      : AMD EPYC 7401P 24-Core Processor
```
with Gigabyte board:

```
Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
        Manufacturer: GIGABYTE
        Product Name: MZ31-AR0-00
        Version: 01010101
        Serial Number: HHAN6600046
        Asset Tag: 01234567890123456789AB
        Features:
                Board is a hosting board
                Board is removable
                Board is replaceable
        Location In Chassis: 01234567890123456789AB
        Chassis Handle: 0x0003
        Type: Motherboard
        Contained Object Handles: 0
```
`sensors-detect` outputs following
```
Driver `k10temp':
  * Chip `AMD Family 17h thermal sensors' (confidence: 9)

Driver `to-be-written':
  * ISA bus, address 0xca2
    Chip `IPMI BMC KCS' (confidence: 8)
```
currently I'm running on Linux Kernel `4.14.13-1~bpo9+1`. Is it possible to configure `sensors` without recompiling kernel? How do I write IPMI driver?

**Comment by groeck** [comment]
'sensors' is a user-space program. It is configured with /etc/sensors3.conf. It is never necessary to recompile the kernel to configure it.
To write a driver, first you need its documentation, then write a driver as you would write any other Linux kernel driver. However, IPMI is not just about writing a driver, as you may notice if you research Linux IPMI support. I would suggest to research if any of the available IPMI packages supports the chip on your board. This has nothing to do with lm-sensors or sensors-detect; sensors-detect only reports what is there, it doesn't implement it.

**Comment by deric** [comment]
@groeck Thanks! It looks like the [MZ31-AR0 motherboard](http://b2b.gigabyte.com/Server-Motherboard/MZ31-AR0-rev-10#ov) supports only remote management through Gigabyte's BMC interface. I'll try to look into impi tools.

**Comment by groeck** [comment]
lbipmimonitoring is used by ipmimonitoring(8)  which has its own configuration file. The functionality therefore already exists. It might possibly make sense to merge the two, but that would have to be driven by the maintainers of ipmimonitoring. Otherwise it simply does not make sense to create a parallel infrastructure to solve the same problem.
