### ISSUE TITLE
Overheating detection?

### ISSUE THREAD

**Issue by Yvan-Masson** [groeck/lm-sensors#73]
Hi,

I am not able to read C, so I can't answer this question myself: does `sensors` provides a mechanism to know if temperature exceed thresholds? I was thinking about returning an error code.

- If it is, could this be added to the manpage?
- If not, could such a detection be added?

Thanks for you time and work,
Yvan

**Comment by groeck** [comment]
The sensors command reports the status of alarm attributes. Its responsibility is reporting values. Exceeding limits is, from the perspective of the sensors command, not an error. Having it return an error code would not be appropriate.
