### ISSUE TITLE
Out-of-date repo description

### ISSUE THREAD

**Issue by jwilk** [groeck/lm-sensors#75]
Description of this GitHub repository reads:
> Clone of lm-sensors svn repository 

But in e0e2d2d787d8d86fad1d3c545fbf487605903bd6 you said:
> The package is no longer maintained in svn.

**Comment by groeck** [comment]
Thanks for the information. Even better would be if you would send a pull request to fix it.

**Comment by leighbb** [comment]
I think the description can only be edited through the web interface, unfortunately.

**Comment by groeck** [comment]
Good point. Updated.
