### ISSUE TITLE
Non-hwmon data source for lm_sensors

### ISSUE THREAD

**Issue by markusha** [groeck/lm-sensors#78]
Hello.
I'm trying to setup fancontrol for it to control one PWM fan based on GPU temperature. The thing is that I'm using proprietary nVidia drivers and because of this apparently lm_sensors do not provide GPU temperature data. However together with the drivers a tool "nvidia-smi" is provided which can print GPU temperature to stdout (and at certain interval if needed). So I'm wondering, is it possible to somehow hook up the output from this tool as data source for lm_sensors/fancontrol/pwmconfig (without modifying any sources that is)?

**Comment by groeck** [comment]
Sorry, no, that does not work. You would have to modify sensors/fancontrol/pwmconfig to read the output from the proprietary tool.
