### ISSUE TITLE
Add sensors from CoreBoot  project

### ISSUE THREAD

**Issue by Saentist** [groeck/lm-sensors#86]
https://github.com/coreboot/coreboot/tree/master/src/superio
there are lot of sensors

also project have motherboard profiles
* https://www.coreboot.org/Supported_Motherboards
* https://www.coreboot.org/Supported_Chipsets_and_Devices

**Comment by groeck** [comment]
The information avalable in coreboot is often insufficient for writing an actual driver. Plus, support for specific sensors would typically be added to the Linux kernel in the form of separate Linux kernel drivers, one per chip or chip family. Patches to do that will happily be reviewed and accepted by the Linux kernel hwmon subsystem maintainer. However, this is not an issue to be addressed withing the lm-sensors repository.
Actionable issues in the contet of lm-sensors might be something like "Super-IO chip X on motherboard Y not detected", with accompanying information such as the output of sensors-detect. But "this other project supports X, you should support it as well" is neither reasonable nor actionable.
