### ISSUE TITLE
LM-Sensors does not parse gpu info

### ISSUE THREAD

**Issue by pager72** [groeck/lm-sensors#97]
Lots of goodies are found in:
/sys/kernel/debug/dri/0/amdgpu_pm_info

including gpu temp, volts and frequency.

**Comment by groeck** [comment]
LM sensors uses the hardware monitoring ABI to obtain the information it displays. It does not try to decode random non-standardized debug data which may change anytime. If the referenced debugfs file reports data which is not made available via the hardware monitoring ABI, the AMD GPU driver should be updated to fix that.
