### ISSUE TITLE
NCT6793 - Can't switch PWM mode

### ISSUE THREAD

**Issue by DocMAX** [groeck/lm-sensors#98]
On this chip i can't change the mode.
Doing echo 0 > pwm1_mode doesn't change pwm1_mode to "0".
It remains on value "1"

My mainboard is ASUS PRIME J3355.

Thanks.

**Comment by groeck** [comment]
Sigh. Do you really think that opening the same problem all over the place is going to get it fixed faster ?

**Comment by DocMAX** [comment]
I wasn't sure which of both is the active one. Sorry.
